### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by zenhack** [Glow-Lang/glow#425]
...since I don't think we have an issue tracking this already.

I tried to fix this in #423, but it looks like not finding the *shell* isn't the issue.

It appears that there are no files matching `/etc/*release`, which the checkout action is looking for.

Where is the code that actually builds the docker image?

**Comment by AlexKnauth** [comment]
The code that builds the docker image is in https://github.com/fare/gerbil-utils/blob/master/scripts/make-docker-image.ss
and that's what I'm attempting to fix today.

**Comment by AlexKnauth** [comment]
Working on it in https://github.com/Glow-Lang/glow/pull/428
